[pytest]
testpaths = tests
python_files = test_*.py
addopts = -p no:cacheprovider
filterwarnings =
    ignore::DeprecationWarning:fastapi.*
    ignore::starlette.exceptions.StarletteDeprecationWarning

